#!/bin/bash

echo "esp self-update script: used to install updates to esp from a temporary location to /usr/bin/esp."

if [ "$EUID" -ne 0 ]
then
    echo "This script must be run as root!"
    exit
fi

if [ -f "/usr/bin/esp_temp" ]
then
    mv /usr/bin/esp_temp /usr/bin/esp
    chmod +x /usr/bin/esp
    echo "Finished installing esp."
else
    echo "A temporary version of esp could not be found!"
fi