#!/bin/bash

echo "esp uninstall script: used to uninstall esp."

if [ "$EUID" -ne 0 ]
then
    echo "This script must be run as root!"
    exit
fi

if [ -f "/usr/bin/esp" ]
then
    rm /usr/bin/esp*
    echo "Finished uninstalling esp."
fi